# This is the configuration for your SEOSiri backend on Fly.io

app = 'backend-frosty-violet-5653'
primary_region = 'sin'

[build]
  builder = "paketobuildpacks/builder:base"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

# This is the command that starts your Python server
[processes]
  app = "uvicorn main:app --host 0.0.0.0 --port 8080"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1